<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.mXG07VD' shared service.

return $this->privates['service_locator.mXG07VD'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('customerRepository' => function (): ?\App\Repository\CustomerRepository {
    return ($this->privates['App\Repository\CustomerRepository'] ?? $this->load(__DIR__.'/getCustomerRepositoryService.php'));
}));
