<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTcOtzgP\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTcOtzgP/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTcOtzgP.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTcOtzgP\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTcOtzgP\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TcOtzgP',
    'container.build_id' => 'c85cb70e',
    'container.build_time' => 1527958293,
));
